### ISSUE TITLE
janggi bikjang Rule Problem

### ISSUE THREAD

**Issue by kimqwer2** [gbtami/Fairy-Stockfish#22]
Hello. I am Korean. 
I don't know English and use a translator.
There is a rule called bikjang in Korean janggi, but it seems to be wrong in this program.
The bikjang is a rule that allows the intestines to eat and make it a draw.
for example
![캡처](https://user-images.githubusercontent.com/63884391/79623167-a776b780-8155-11ea-8f43-dc4ae61116f9.PNG)
In this case, white is very disadvantageous.
But white has a rule called bikjang.
White can be used to make a draw using a bikjang.
If the white moves to the right, the black head has nowhere to move.
bikjang
![캡처](https://user-images.githubusercontent.com/63884391/79624038-1bb35a00-815a-11ea-9152-76e73a4e47b6.PNG)
or
Even if the black escapes, the white will bikjang and become a draw.
![캡처](https://user-images.githubusercontent.com/63884391/79624084-68973080-815a-11ea-9ba9-1633d5f69297.PNG)
So black is very advantageous, but there is a bikjang,
We have to eat the white palace with the black palace and make it a draw.
in other cases (When it is black turn, The photo above is bikjang because it is the turn of the white.)
![캡처](https://user-images.githubusercontent.com/63884391/79623383-e8230080-8156-11ea-8bf9-d2aef675fa07.PNG)
In this case, black should not bikjang.
Like the picture above, you have to block the path of the palace and block the bikjang.
But this program is black trying to bikjang.
![캡처](https://user-images.githubusercontent.com/63884391/79623871-6da7b000-8159-11ea-8b99-ef331f061999.PNG)
Black tries to bikjang despite its advantage, so the winning game becomes a draw.
Therefore, I think the ganggi rule of Fairy-Stockfish is a little strange in this part.
In addition, it is popular in Korea that there is no bikjang, and bikjang is often used in janggi competitions.
It would be nice if you could choose the bikjang rule.
thank you for your interest in Korean janggi.

**Comment by kimqwer2** [comment]
> Hello. I am Korean.
> I don't know English and use a translator.
> There is a rule called bikjang in Korean janggi, but it seems to be wrong in this program.
> The bikjang is a rule that allows the intestines to eat and make it a draw.
> for example
> ![캡처](https://user-images.githubusercontent.com/63884391/79623167-a776b780-8155-11ea-8f43-dc4ae61116f9.PNG)
> In this case, white is very disadvantageous.
> But white has a rule called bikjang.
> White can be used to make a draw using a bikjang.
> If the white moves to the right, the black head has nowhere to move.
> So black is very advantageous, but there is a bikjang,
> We have to eat the white palace with the black palace and make it a draw.
> So don't make a big bang if you have an advantage.
> in other cases
> ![캡처](https://user-images.githubusercontent.com/63884391/79623383-e8230080-8156-11ea-8bf9-d2aef675fa07.PNG)
> Black tries to bikjang despite its advantage, so the winning game becomes a draw.
> Therefore, I think the ganggi rule of Fairy-Stockfish is a little strange in this part.
> In addition, it is popular in Korea that there is no bikjang, and bikjang is often used in janggi competitions.
> It would be nice if you could choose the bikjang rule.

**Comment by ianfab** [comment]
closing due to ianfab/Fairy-Stockfish#101
